language: php

# faster builds on new travis setup not using sudo
sudo: false

php:
  - 7.0

install:
  - travis_retry composer install --prefer-source --no-interaction

script:
  - phpunit --colors=always .